# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18IY6sSscIakMYDaTInbffXZo2uBKEDJm
"""

from google.colab import files

uploaded = files.upload()

import pandas as pd
import numpy as np

movies = pd.read_csv("ml-latest-small/movies.csv")
movies.head()

movies.info()

movies['genres'] = movies['genres'].str.replace('|', ' ', regex=False)
movies.head()

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(stop_words='english')

tfidf_matrix = tfidf.fit_transform(movies['genres'])

from sklearn.metrics.pairwise import cosine_similarity

cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)

indices = pd.Series(movies.index, index=movies['title']).drop_duplicates()

def recommend_movies(title, cosine_sim=cosine_sim):

    # error handling
    if title not in indices:
        return "Movie not found in dataset"

    # get index of the movie
    idx = indices[title]

    # similarity scores
    sim_scores = list(enumerate(cosine_sim[idx]))

    # sort movies by similarity
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    # remove the same movie & take top 10
    sim_scores = sim_scores[1:11]

    # get movie indices
    movie_indices = [i[0] for i in sim_scores]

    return movies['title'].iloc[movie_indices]

recommend_movies("Toy Story (1995)")

recommend_movies("Pathaan")

